### ISSUE TITLE
Need precompiled VoodooI2CElan and VoodooGPIO with patches.

### ISSUE THREAD

**Issue by jarryson** [isi95010/DrallionMacOS#2]
First of all, thanks so much for your project, it saves so much time.

but i still need some help. 

Need precompiled VoodooI2CElan and VoodooGPIO with patches your menthioned. A build environment is to difficult for me and I think bin files are complete the same.

Thanks again!

**Comment by jarryson** [comment]
my bad, I spend days try to build a compile environment, 

I tried catalina and homebrew, it said catalina is not supported and install coffeescript failed which is a dependency of cldoc (a build dependency of VoodooI2C). It showed some errors, some thing like minimal os needs 11.0. I tried monterey and still  build cldoc failed.

Doing such thing is not easy for non english speaker nor no development experience.

i searched a lot,  finally successful. no need compile VoodooI2C, just compiled VoodooI2CELAN and VoodooGPIO(latest git, (double checked with patches you said) using VoodooI2C version 2.8 , but still cannot get touch screen and touchpad working. Am I doing some steps wrong?

Really need precompiled kexts please.

**Comment by jarryson** [comment]
I replaced VoodooI2CELAN and VoodooGPIO and recompiled the whole VoodooI2C. And It finally worked.

PS: There is a typo in the instruction. Base \_SB.PCI0.I2C**0**.D015 should be \_SB.PCI0.I2C**1**.D015

**Comment by isi95010** [comment]
Thanks for pointing out the typo! 
I'm glad you got it to work. Hopefully VoodooI2C will have a release soon with those commits to VoodooGPIO and VoodooI2CElan. 
For further support, please reach out at the [Chrultrabook Forum](https://forum.chrultrabook.com/).
