### ISSUE TITLE
black screen after sleep or "pmset displaysleepnow"

### ISSUE THREAD

**Issue by jarryson** [isi95010/DrallionMacOS#3]
After sleep or "pmset displaysleepnow", system still responsible, and backlight works, but screen shows nothing.

I tried "MacBookAir9,1" instead of "MacBookPro15,4", and "00009B3E" out of "0900A53E", and many other config in deviceproperties. But nothing works.

I am using Custom macOS fullrom from https://ethanthesleepy.one/macos/, version [coreboot_edk2-drallion-mrchromebox_20240714_macos.rom](https://ethanthesleepy.one/public/mac_build/coreboot_edk2-drallion-mrchromebox_20240714_macos.rom)

Is this normal or a known issue?

**Comment by isi95010** [comment]
Again, @jarryson, I'm asking you NOT to request configuration help here on Github. Simply tag my user name at the Chrultrabook forum and I'll try to help there.
